const books = [
    {
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        isbn: "9780062457714",
        genre: "Personal Development",
        price: (16.99 * 10.50).toFixed(2), // 178.39 MAD
        publicationYear: 2016,
        publisher: "HarperOne",
        language: "English",
        pages: 224,
        description: "A counterintuitive approach to living a good life, focusing on the importance of accepting life’s challenges.",
        stock: 25,
        rating: 4.6,
        coverType: "Paperback",
        imageUrl: "../images/book1.jpg",
    },
    {
        title: "The Power of Your Subconscious Mind",
        author: "Joseph Murphy",
        isbn: "9781401912149",
        genre: "Personal Development",
        price: (14.99 * 10.50).toFixed(2), // 157.39 MAD
        publicationYear: 1963,
        publisher: "TarcherPerigee",
        language: "English",
        pages: 288,
        description: "A guide to unlocking the potential of your subconscious mind to achieve success, happiness, and health.",
        stock: 18,
        rating: 4.7,
        coverType: "Paperback",
        imageUrl: "../images/book3.jpg",
    },
    {
        title: "The Power of Habit",
        author: "Charles Duhigg",
        isbn: "9781400069286",
        genre: "Personal Development",
        price: (16.00 * 10.50).toFixed(2), // 168.00 MAD
        publicationYear: 2012,
        publisher: "Random House",
        language: "English",
        pages: 400,
        description: "Explores the science of habit formation and how you can change habits to transform your life.",
        stock: 30,
        rating: 4.5,
        coverType: "Hardcover",
        imageUrl: "../images/book6.jpg",
    },
    {
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        isbn: "9781612680194",
        genre: "Personal Development",
        price: (14.95 * 10.50).toFixed(2), // 156.98 MAD
        publicationYear: 1997,
        publisher: "Warner Books",
        language: "English",
        pages: 207,
        description: "A personal finance classic that contrasts the mindsets of two fathers—one rich, one poor—to teach financial literacy.",
        stock: 22,
        rating: 4.7,
        coverType: "Paperback",
        imageUrl: "../images/book4.jpg",
    },
    {
        title: "Atomic Habits",
        author: "James Clear",
        isbn: "9780735211292",
        genre: "Personal Development",
        price: (16.99 * 10.50).toFixed(2), // 178.39 MAD
        publicationYear: 2018,
        publisher: "Avery",
        language: "English",
        pages: 320,
        description: "A practical guide to breaking bad habits and building good ones through small, incremental changes.",
        stock: 40,
        rating: 4.8,
        coverType: "Hardcover",
        imageUrl: "../images/book5.jpg",
    },
    {
        title: "Deep Work",
        author: "Cal Newport",
        isbn: "9781455586691",
        genre: "Personal Development",
        price: (17.00 * 10.50).toFixed(2), // 178.50 MAD
        publicationYear: 2016,
        publisher: "Grand Central Publishing",
        language: "English",
        pages: 304,
        description: "Focuses on the importance of deep, concentrated work for achieving extraordinary success in a distracted world.",
        stock: 15,
        rating: 4.6,
        coverType: "Hardcover",
        imageUrl: "../images/book2.jpg",
    },
    {
        title: "Moby-Dick",
        author: "Herman Melville",
        isbn: "9781503280786",
        genre: "Fantasy",
        price: (11.99 * 10.50).toFixed(2), // 125.89 MAD
        publicationYear: 1851,
        publisher: "CreateSpace Independent Publishing Platform",
        language: "English",
        pages: 635,
        description: "The classic tale of Captain Ahab’s obsessive quest to kill the white whale, Moby-Dick.",
        stock: 12,
        rating: 4.3,
        coverType: "Paperback",
        imageUrl: "../images/book7.jpg",
    },
];

export default books;
