const books = [
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        isbn: "9780061120084",
        genre: "Fiction",
        price: 14.99,
        publicationYear: 1960,
        publisher: "J.B. Lippincott & Co.",
        language: "English",
        pages: 281,
        description: "A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in the South.",
        stock: 10,
        rating: 4.8,
        coverType: "Paperback",
        imageUrl: "https://picsum.photos/200/300"
    },
    {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        isbn: "9780547928227",
        genre: "Fantasy",
        price: 12.99,
        publicationYear: 1937,
        publisher: "George Allen & Unwin",
        language: "English",
        pages: 310,
        description: "Bilbo Baggins embarks on an adventure that changes his life forever.",
        stock: 15,
        rating: 4.7,
        coverType: "Hardcover",
        imageUrl: "https://picsum.photos/200/300"
    },
    {
        title: "1984",
        author: "George Orwell",
        isbn: "9780451524935",
        genre: "Dystopian",
        price: 9.99,
        publicationYear: 1949,
        publisher: "Secker & Warburg",
        language: "English",
        pages: 328,
        description: "A dystopian novel exploring the dangers of totalitarianism.",
        stock: 25,
        rating: 4.6,
        coverType: "Paperback",
        imageUrl: "https://picsum.photos/200/300"
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        isbn: "9780316769488",
        genre: "Classic",
        price: 13.49,
        publicationYear: 1951,
        publisher: "Little, Brown and Company",
        language: "English",
        pages: 277,
        description: "A story about adolescent alienation and rebellion.",
        stock: 18,
        rating: 4.4,
        coverType: "Paperback",
        imageUrl: "https://picsum.photos/200/300"
    },
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        isbn: "9780141439518",
        genre: "Romance",
        price: 10.99,
        publicationYear: 1813,
        publisher: "T. Egerton",
        language: "English",
        pages: 432,
        description: "A classic tale of love and misunderstandings.",
        stock: 20,
        rating: 4.9,
        coverType: "Hardcover",
        imageUrl: "https://picsum.photos/200/300"
    },
    {
        title: "The Alchemist",
        author: "Paulo Coelho",
        isbn: "9780061122415",
        genre: "Adventure",
        price: 16.99,
        publicationYear: 1988,
        publisher: "HarperCollins",
        language: "English",
        pages: 208,
        description: "A fable about following your dreams and finding your destiny.",
        stock: 12,
        rating: 4.7,
        coverType: "Paperback",
        imageUrl: "https://picsum.photos/200/300"
    }
];


export default books;